language: php
sudo: false
php:
- 5.4
- 5.6
branches:
  only:
  - master
  - develop
  - obsman
matrix:
  allow_failures:
  - php: 5.6
  - env: ALLOW_FAILURE=true
install:
- composer install --optimize-autoloader --prefer-dist --no-interaction
script:
- make codestyle
- make security-check
- make test
