language: php
sudo: false
php:
- 5.6
- 7.0
branches:
  only:
  - master
matrix:
  allow_failures:
  - php: 5.6
  - env: ALLOW_FAILURE=true
install:
- composer install --optimize-autoloader --prefer-dist --no-interaction
script:
